### ISSUE TITLE
What's the GoogleFileID?

### ISSUE THREAD

**Issue by Ze-Yang** [chentinghao/download_google_drive#4]
What's the GoogleFileID for this link `https://drive.google.com/file/d/1vTOYx8_rSNwjQ3Tt95b795GFATFaf6Wx/view?usp=sharing`?

**Comment by MitchellX** [comment]
1vTOYx8_rSNwjQ3Tt95b795GFATFaf6Wx

**Comment by chentinghao** [comment]
@MitchellX is correct.
This website can help you generate the link same as the guide that I provided. Hope it helps.
https://sites.google.com/site/gdocs2direct/home
