### ISSUE TITLE
download again question

### ISSUE THREAD

**Issue by DJ543** [chentinghao/download_google_drive#5]
Hi, thanks for the script.
I download a file successfully,but I ctrl-c to stop it. Then I try to download again fail. why the same command just download 32KB in the second time and finish? and then i try to download other files,which also download 32KB and finish incorrectly.
Thanks for your help

**Comment by chentinghao** [comment]
If you are downloading the same file with the same GoogleFileID, then you are good to go. On the other hand, please make sure you are using different GoogleFileID for different files.
