### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by Marietto2008** [chentinghao/download_google_drive#6]
root@Z390-AORUS-PRO:/home/ziomario/Scrivania/Virt/cont/docker/download_google_drive# python download_gdrive.py 1fJrRRSc8VxW3g7rnh-70fovtUWn0SIm vm
Traceback (most recent call last):
  File "download_gdrive.py", line 12, in <module>
    import requests
ImportError: No module named requests

root@Z390-AORUS-PRO:/home/ziomario/Scrivania/Virt/cont/docker/download_google_drive# python
Python 2.7.18 (default, Mar  9 2021, 11:09:26) 
[GCC 10.2.1 20210306] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
[1]+  Stopped                 python

root@Z390-AORUS-PRO:/home/ziomario/Scrivania/Virt/cont/docker/download_google_drive# python3
Python 3.9.4 (default, Apr  4 2021, 19:38:44) 
[GCC 10.2.1 20210401] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
KeyboardInterrupt
>>> 
[2]+  Stopped                 python3

root@Z390-AORUS-PRO:/home/ziomario/Scrivania/Virt/cont/docker/download_google_drive# python3 download_gdrive.py 1fJrRRSc8VxW3g7rnh-70fovtUWn0SIm vm
#download_gdrive.py:50: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(sys.argv) is not 3:
Traceback (most recent call last):
  File "/home/ziomario/Scrivania/Virt/cont/docker/download_google_drive/download_gdrive.py", line 14, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

**Comment by chentinghao** [comment]
As your errors suggested, you have to install some missing packages to run the code.

`pip install requests`
`pip install tqdm`

**Comment by Marietto2008** [comment]
root@Z390-AORUS-PRO:/home/ziomario/Scrivania/Virt/cont/docker/gdown.pl# pip install requests
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (2.25.1)

root@Z390-AORUS-PRO:/home/ziomario/Scrivania/Virt/cont/docker/gdown.pl#  pip install tqdm
Collecting tqdm
  Downloading tqdm-4.60.0-py2.py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 2.0 MB/s 
Installing collected packages: tqdm
Successfully installed tqdm-4.60.0

root@Z390-AORUS-PRO:/home/ziomario/Scrivania/Virt/cont/docker/download_google_drive# python download_gdrive.py 1fJrRRSc8VxW3g7rnh-70fovtUWn0SIm vm
Traceback (most recent call last):
  File "download_gdrive.py", line 12, in <module>
    import requests
ImportError: No module named requests
