### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Soooda** [chentinghao/download_google_drive#8]
I was using the python script to download a dataset from Google Drive and I think I've done everything correctly but the downloaded file is always 32KB only. Any clues?

The dataset is [ATD-12K](https://drive.google.com/file/d/1XBDuiEgdd6c0S4OXLF4QvgSn_XNPwc-g/view)

**Comment by tungngovn** [comment]
I also met the same problem. It is a new error because I have used this repo for a long time without any problem.

**Comment by nikoletta-toth** [comment]
If you look into the downloaded file, you can see that GDrive gives a : "Google Drive - Virus scan warning" message. 
In the browser you also get that, in which case you can click : download anyway.
However, in our case the downloader just downloads this message as an html page, instead of the file you actually want to download.

**Comment by Soooda** [comment]
> If you look into the downloaded file, you can see that GDrive gives a : "Google Drive - Virus scan warning" message. In the browser you also get that, in which case you can click : download anyway. However, in our case the downloader just downloads this message as an html page, instead of the file you actually want to download.

Cheers, it makes sense now. But are there any walk-arounds?

**Comment by rmchurch** [comment]
Work-around, change URL to this:
```
URL = "https://docs.google.com/uc?export=download&confirm=9iBg"
```

**Comment by Soooda** [comment]
> Work-around, change URL to this:
> 
> ```
> URL = "https://docs.google.com/uc?export=download&confirm=9iBg"
> ```

Cheers, solved my issue, may I ask will the `confirm=9iBg` always hold for any files coming from Google Drive?

**Comment by rmchurch** [comment]
Not sure, I found this by going to the download page of the file, which states its too large for virus scan, and right-clicked on the Download Anyway button to "Inspect", and found the link. In the future it may change, and perhaps needs to be a secondary input with the Google Drive fileID

**Comment by Soooda** [comment]
> Not sure, I found this by going to the download page of the file, which states its too large for virus scan, and right-clicked on the Download Anyway button to "Inspect", and found the link. In the future it may change, and perhaps needs to be a secondary input with the Google Drive fileID

Right, this should be useful for all cases. Thank you!

**Comment by MayYoY** [comment]
> Work-around, change URL to this:
> 
> ```
> URL = "https://docs.google.com/uc?export=download&confirm=9iBg"
> ```

it doesn't seem to work when downloading a folder :(
